# -*- coding: utf-8 -*-
"""compute_input.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c0Zu8FPgTDMLIrCRHS7PatgnbeHuEmju
"""

## compute_input.py

import sys, json, numpy as np
import pandas as pd
from prophet import Prophet

#Read data from stdin
def read_in():
    lines = sys.stdin.readlines()
    #Since our input would only be having one line, parse our JSON data from that
    return json.loads(lines[0])

def main():
    #get our data as an array from read_in()
    lines = read_in()

    #create a numpy array
    np_lines = np.array(lines)

    #use numpys sum method to find sum of all elements in the array
    lines_sum = np.sum(np_lines)
    lines_first = np_lines[0]

    #return the sum to the output stream
    output = [lines_sum, lines_first]
    print(output)

#start process
if __name__ == '__main__':
    main()